/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

 import React, { Component } from 'react';
 import { Platform, StyleSheet, Text, View,Button } from 'react-native';
 import GmsAutoPlacePicker from 'react-native-google-auto-complete-place-picker';
 
 export default class App extends Component<{}> {
   state = {
     status: 'starting',
     message: '--'
   };
   componentDidMount() {
   }
   
   pickPlace = () => {
     GmsAutoPlacePicker.pickPlace().then((placeData)=>{
       console.log("place data >>",placeData)
     })
   }
   
 
   render() {
     return (
       <View style={styles.container}>
         <Button title = "Pick place" onPress={this.pickPlace}/>
       </View>
     );
   }
 }
 
 const styles = StyleSheet.create({
   container: {
     flex: 1,
     justifyContent: 'center',
     alignItems: 'center',
     backgroundColor: '#F5FCFF',
   },
   welcome: {
     fontSize: 20,
     textAlign: 'center',
     margin: 10,
   },
   instructions: {
     textAlign: 'center',
     color: '#333333',
     marginBottom: 5,
   },
 });
 