/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

 import React, { Component } from 'react';
 import { Platform, StyleSheet, Text, View,Button } from 'react-native';
 import GoogleAutoCompletePlacePicker from 'react-native-google-auto-complete-place-picker';
 
 export default class App extends Component {
   state = {
     locationResult : ""
   };
   componentDidMount() {
   }
   
   pickPlace = () => {
    GoogleAutoCompletePlacePicker.pickPlace().then((placeData)=>{
       console.log("place data >>",placeData)
       this.setState({locationResult:JSON.stringify(placeData)})
     }).catch((error)=>{
       console.log(JSON.stringify(error))
     })
   }
   
 
   render() {
     return (
       <View style={styles.container}>
         <Button title = "Pick place" onPress={this.pickPlace}/>
         <Text style={styles.txtStyle}>{"Location result :- "+this.state.locationResult}</Text>
       </View>
     );
   }
 }
 
 const styles = StyleSheet.create({
   container: {
     flex: 1,
     justifyContent: 'center',
     alignItems: 'center',
     backgroundColor: '#F5FCFF',
   },
   txtStyle: {
     alignSelf: 'center',
     marginTop:20,
     width:"70%",
     fontSize:15
   },
 });
 